logging.config=classpath:logback-spring.xml
server.shutdown=graceful
spring.main.banner_mode=off
# actuators
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health
management.metrics.web.client.request.autotime.enabled=false
management.health.jms.enabled=true