kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  filesFrom:
    - secret: {{ DOKDISTDPV_SECRETS }}
      mountPath: /var/run/secrets/nais_secrets
  envFrom:
    - secret: {{ DOKDISTDPV_SECRETS }}
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              -Djavax.net.ssl.keyStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.keyStorePassword=$(NAV_TRUSTSTORE_PASSWORD)
              -Djavax.net.ssl.keyStoreType=jks
              --enable-preview
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: DOKDISTDPV_JMS_BROKER_HOSTNAME
      value: {{ DOKDISTDPV_JMS_BROKER_HOSTNAME }}
    - name: DOKDISTDPV_JMS_BROKER_NAME
      value: {{ DOKDISTDPV_JMS_BROKER_NAME }}
    - name: DOKDISTDPV_JMS_BROKER_PORT
      value: "{{ DOKDISTDPV_JMS_BROKER_PORT }}"
    - name: DOKDISTDPV_JMS_BROKER_CHANNEL
      value: {{ DOKDISTDPV_JMS_BROKER_CHANNEL }}
    - name: DOKDISTDPV_JMS_QUEUES_QDIST016
      value: {{ DOKDISTDPV_JMS_QUEUES_QDIST016 }}
    - name: DOKDISTDPV_JMS_QUEUES_QDIST016_FUNKSJONELL_FEIL
      value: {{ DOKDISTDPV_JMS_QUEUES_QDIST016_FUNKSJONELL_FEIL }}
    - name: DOKDISTDPV_JMS_QUEUES_QDIST016_TEKNISK_FEIL
      value: {{ DOKDISTDPV_JMS_QUEUES_QDIST016_TEKNISK_FEIL }}
    - name : DOKDISTDPV_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTDPV_ENDPOINTS_DOKDISTADMIN_URL }}
    - name : DOKDISTDPV_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTDPV_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name : DOKDISTDPV_ENDPOINTS_DOKARKIV_URL
      value: {{ DOKDISTDPV_ENDPOINTS_DOKARKIV_URL }}
    - name : DOKDISTDPV_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ DOKDISTDPV_ENDPOINTS_DOKARKIV_SCOPE }}
    - name : DOKDISTDPV_ENDPOINTS_SAF_URL
      value: {{ DOKDISTDPV_ENDPOINTS_SAF_URL }}
    - name : DOKDISTDPV_ENDPOINTS_SAF_SCOPE
      value: {{ DOKDISTDPV_ENDPOINTS_SAF_SCOPE }}
    - name : DOKDISTDPV_ENDPOINTS_ALTINN3_URL
      value: {{ DOKDISTDPV_ENDPOINTS_ALTINN3_URL }}
    - name : DOKDISTDPV_ENDPOINTS_ALTINN3_SCOPE
      value: {{ DOKDISTDPV_ENDPOINTS_ALTINN3_SCOPE }}
    - name : DOKDISTDPV_TOPIC_ALTINN_MELDING_HENDELSE
      value: {{ DOKDISTDPV_TOPIC_ALTINN_MELDING_HENDELSE }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/run/secrets/nais_secrets/gcloud_serviceaccount.json"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 60m
      memory: 2Gi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ KAFKA_POOL }}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner"
        - name: "altinn:correspondence.write"
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system