dokdistmellomlager.projectid=test
dokdistmellomlager.bucket=test
dokdistmellomlager.keyring=test
dokdistmellomlager.keyid=test
dokdistdpv.serviceuser.username=srvdokdistdpv
dokdistdpv.serviceuser.password=pw
dokdistdpv.jms.broker.hostname=test
dokdistdpv.jms.broker.port=1
dokdistdpv.jms.broker.name=test
dokdistdpv.jms.broker.channel=test
dokdistdpv.jms.queues.qdist016=test
dokdistdpv.jms.queues.qdist016FunksjonellFeil=test
dokdistdpv.jms.queues.qdist009=test

altinn.insert.correspondence.service.endpoint="http://localhost:${wiremock.server.port}/ServiceEngineExternal/CorrespondenceAgencyExternalEC2.svc",
altinn.servicecode.externalservicecode: "5828",
altinn.servicecode.externalserviceiditionecode: "1"

