name: Build, push, and deploy

on:
  workflow_dispatch:

jobs:
#  build:
#    uses: navikt/dok-workflows/.github/workflows/build.yaml@main
#    with:
#      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
#    secrets: inherit

  deploy-q1:
    uses: navikt/dok-workflows/.github/workflows/deploy-dev.yaml@main
    needs: build
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      NAIS_VARIABLES: nais/q1-config.json
    secrets: inherit
