name: Deploy release to prod

on:
  release:
    types:
      - published

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    uses: navikt/dok-workflows/.github/workflows/build.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  deploy-prod:
    uses: navikt/dok-workflows/.github/workflows/deploy.yaml@main
    needs: build
    with:
      NAIS_CLUSTER: prod-fss
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      NAIS_RESOURCE: nais/naiserator.yaml
      NAIS_VARIABLES: nais/p-config.json
    secrets: inherit
