name: Build, push, and deploy

on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    uses: navikt/dok-workflows/.github/workflows/build.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  deploy-q1:
    uses: navikt/dok-workflows/.github/workflows/deploy.yaml@main
    needs: build
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      NAIS_RESOURCE: nais/naiserator.yaml
      NAIS_VARIABLES: nais/q1-config.json
    secrets: inherit

#  call-deploy-q2-workflow:
#    uses: navikt/dok-workflows/.github/workflows/deploy.yaml@main
#    needs: call-build-workflow
#    with:
#      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
#      NAIS_RESOURCE: nais/naiserator.yaml
#      NAIS_VARIABLES: nais/q2-config.json
#    secrets: inherit
